title: A-LIEP
preposition: at
description: >-
  Advancing Library and Information Education and Practice in Asia and the Pacific
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://example.com" # the base hostname & protocol for your site, e.g. https://example.com

theme: jekyll-theme-conference

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: false
    permalink: /:collection/:title/
  speakers:
    output: false
    permalink: /:collection/:title/
  rooms:
    output: false
    permalink: /:collection/:title/
  "2019":
    output: true
    permalink: /:collection/:title/



defaults:
  - scope:
      path: ""
      type: calls
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Timezone
  tz: "+02:00"

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: A-LIEP
      img: 'A-LLIEP LOGO.png'
      url: 'https://a-liep.org/'
    breakpoint: md
    links:
      - name: About A-LIEP
        relative_url: /about/
      - name: Past Conferences
        menu:
          - name: 2023 (current)
            disabled: true
          - name: "2021"
            disabled: true
            subfolderitems:
              - page: Articles/News
                url: /2021/articles.html
              - page: Proceedings
                url: /2021/proceedings.html
              - page: Photos
                url: /2021/photos.html
          - name: "2019"
            disabled: true
            subfolderitems:
              - page: Articles/News
                url: /2019/articles.html
              - page: Proceedings
                url: /2019/proceedings.html
              - page: Photos
                url: /2019/photos.html
  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
      # img: "assets/images/A-LLIEP LOGO.png"

    links:
      - name: Call for Papers
        relative_url: /calls/
      - name: Tracks
        relative_url: /tracks/
      - name: Venue
        relative_url: /venue/
      - name: Registration
        relative_url: /registration/

  # Information boxes
  # info_bars:
  #   - title: Welcome to the Conference Theme for Jekyll!
  #     color: primary
  #     main_only: true
  #     text: |
  #       The Theme was originally made for the [Winterkongress](https://www.digitale-gesellschaft.ch/kongress/), a yearly conference of the [Digital Society Switzerland](https://digitale-gesellschaft.ch/).
  #
  #       ---
  #
  #       See the [README](github.com/DigitaleGesellschaft/jekyll-theme-conference/) on the project's GitHub repository for further information on how to configure and adapt it to your needs.
  #   - text: This is just some random content for demonstration purposes.
  #     color: warning
  #     pages_only: true

  # Live indications
  live:
    hide: true

    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  talks:
    hide: true

    # Talk categories
    main_categories:
      - name: Cat A
        color: info
      - name: Cat B
        color: success

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    hide: true

    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: true
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    map:
      # Initial map center point
      home_coord: 47.37808, 8.53935
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 17


  program:
    hide: true

    # URL of program page
    # url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    # show_alltimes: true
